# Generated by Django 5.0.3 on 2024-03-18 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.TextField(max_length=2),
        ),
        migrations.AlterField(
            model_name='animal',
            name='intake_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 53, 9, 653005, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 53, 9, 657249, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 11, 53, 9, 655005, tzinfo=datetime.timezone.utc)),
        ),
    ]
