# Generated by Django 5.0.3 on 2024-04-25 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 4, 47, 4, 617002, tzinfo=datetime.timezone.utc)),
        ),
    ]
