# Generated by Django 5.0.3 on 2024-03-20 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_animal_intake_date_alter_comment_time_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='intake_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 16, 41, 15, 253959, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 16, 41, 15, 262535, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 16, 41, 15, 253959, tzinfo=datetime.timezone.utc)),
        ),
    ]
