# Generated by Django 5.0.3 on 2024-03-22 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_animal_intake_date_alter_comment_time_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='intake_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 14, 42, 41, 198778, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 14, 42, 41, 206780, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 14, 42, 41, 198778, tzinfo=datetime.timezone.utc)),
        ),
    ]
