# Generated by Django 5.0.3 on 2024-03-22 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_animal_intake_date_alter_comment_time_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='intake_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 15, 7, 43, 655970, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 15, 7, 43, 663972, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 15, 7, 43, 655970, tzinfo=datetime.timezone.utc)),
        ),
    ]
