# Generated by Django 5.0.3 on 2024-04-01 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_animal_image_alter_animal_intake_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='intake_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 1, 13, 57, 50, 324105, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 1, 13, 57, 50, 327106, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 13, 57, 50, 325106, tzinfo=datetime.timezone.utc)),
        ),
    ]
