# Generated by Django 5.0.3 on 2024-04-04 18:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_animal_intake_date_alter_comment_time_stamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animaltask",
            name="animal",
        ),
        migrations.AddField(
            model_name="task",
            name="animal",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.animal"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 11, 18, 29, 51, 116724, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.DeleteModel(
            name="VaccinationTask",
        ),
        migrations.DeleteModel(
            name="HealthCheckTask",
        ),
        migrations.DeleteModel(
            name="AnimalTask",
        ),
        migrations.DeleteModel(
            name="MicrochippingTask",
        ),
    ]
