# Generated by Django 5.0.3 on 2024-04-04 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_animaltask_animal_remove_animaltask_task_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 18, 41, 10, 799750, tzinfo=datetime.timezone.utc)),
        ),
    ]
