# Generated by Django 5.0.3 on 2024-04-04 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_task_completion_datetime_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 19, 3, 16, 112342, tzinfo=datetime.timezone.utc)),
        ),
    ]
