# Generated by Django 5.0.3 on 2024-04-09 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 14, 54, 48, 211778, tzinfo=datetime.timezone.utc)),
        ),
    ]
