# Generated by Django 5.0.3 on 2024-04-05 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_animal_intake_date_alter_comment_time_stamp_and_more'),
        ('core', '0014_alter_task_due_date'),
    ]

    operations = [
    ]
