# Generated by Django 5.0.3 on 2024-04-04 19:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.animal'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 19, 43, 55, 663602, tzinfo=datetime.timezone.utc)),
        ),
    ]
