# Generated by Django 5.0.3 on 2024-04-11 16:01

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_task_animal_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='comment',
            name='timeStamp',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.person'),
        ),
        migrations.AlterField(
            model_name='task',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.animal'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 16, 1, 5, 205844, tzinfo=datetime.timezone.utc)),
        ),
    ]
