# Generated by Django 5.0.3 on 2024-04-10 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 16, 47, 24, 17200, tzinfo=datetime.timezone.utc)),
        ),
    ]
