# Generated by Django 5.0.3 on 2024-04-11 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_worker_password_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 16, 38, 45, 102876, tzinfo=datetime.timezone.utc)),
        ),
    ]
