# Generated by Django 5.0.3 on 2024-04-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_comment_time_stamp_comment_timestamp_and_more'),
        ('core', '0018_alter_task_due_date'),
    ]

    operations = [
    ]
