# Generated by Django 5.0.3 on 2024-04-11 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20240411_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 17, 42, 17, 101149, tzinfo=datetime.timezone.utc)),
        ),
    ]
