# Generated by Django 5.0.3 on 2024-04-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_task_due_date'),
        ('core', '0021_alter_task_due_date_taskitem'),
    ]

    operations = [
    ]
