# Generated by Django 5.0.3 on 2024-04-18 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merge_20240417_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 17, 42, 18, 969232, tzinfo=datetime.timezone.utc)),
        ),
    ]
